version: "3.8"

services:

  backend:
    build:
      context: .
      dockerfile: ./backend-flask/Dockerfile
    container_name: backend_flask
    image: backend_flask
    volumes:
      - ./backend-flask:/app:z
    ports:
      - "4500:5000"
    environment:
      FRONTEND_URL : "https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      BACKEND_URL : "https://4500-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      OTEL_SERVICE_NAME: 'backend-flask'
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io"
      OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=${HONEYCOMB_API_KEY}"
      AWS_XRAY_URL: "*4500-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}*"
      AWS_XRAY_DAEMON_ADDRESS: "xray-daemon:2000"
      AWS_ACCESS_KEY_ID : "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY : "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION : "${AWS_DEFAULT_REGION}"
      ROLLBAR_API_KEY: "${ROLLBAR_API_KEY}"

  frontend:
    build:
     context: .
     dockerfile: ./frontend-react-js/Dockerfile
    container_name: frontend_react
    image: frontend_react
    volumes:
      - ./frontend-react-js:/app:z
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL : "https://4500-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      REACT_AWS_PROJECT_REGION : "${AWS_DEFAULT_REGION}"
      REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID : "${REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID}"
      REACT_APP_AWS_USER_POOLS_ID : "${REACT_AWS_COGNITO_POOL_ID}"
      REACT_APP_CLIENT_ID : "${REACT_APP_CLIENT_ID}"

  dynamodb-local:
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local"
    container_name: dynamodb-local
    ports:
     - "8000:8000"
    volumes:
       -  ./dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
  
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  
  xray-daemon:
    image: "amazon/aws-xray-daemon"
    environment:
      AWS_ACCESS_KEY_ID : "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY : "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION : "us-west-2"
    command:
      - "xray -o -b xray-daemon:2000"
    ports:
      - "2000:2000/udp"

volumes:
  db:
    driver: local

networks: 
  internal-network:
    driver: bridge
    name: cruddur